<?php

$base = config('path.root');

return [

    # 3rd parties / libraries
    $base.'/vendor/symfony/console/Command/Command.php',
    $base.'/vendor/symfony/console/Input/InputOption.php',
    $base.'/vendor/symfony/console/Input/InputArgument.php',
    $base.'/vendor/robmorgan/phinx/src/Phinx/Console/Command/AbstractCommand.php',
    $base.'/vendor/robmorgan/phinx/src/Phinx/Console/Command/Create.php',
    $base.'/vendor/robmorgan/phinx/src/Phinx/Console/Command/Init.php',
    $base.'/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php',
    $base.'/vendor/robmorgan/phinx/src/Phinx/Console/Command/Rollback.php',
    $base.'/vendor/robmorgan/phinx/src/Phinx/Console/Command/SeedCreate.php',
    $base.'/vendor/robmorgan/phinx/src/Phinx/Console/Command/SeedRun.php',
    $base.'/vendor/robmorgan/phinx/src/Phinx/Console/Command/Status.php',
    $base.'/vendor/robmorgan/phinx/src/Phinx/Console/Command/Test.php',
    $base.'/vendor/vlucas/phpdotenv/src/Dotenv.php',
    $base.'/vendor/vlucas/phpdotenv/src/Loader.php',
    $base.'/vendor/league/tactician/src/Middleware.php',
    // $base.'/vendor/monolog/monolog/src/Monolog/Logger.php',
    // $base.'/vendor/psr/log/Psr/Log/LoggerInterface.php',
    // $base.'/vendor/symfony/console/Helper/HelperSet.php',
    // $base.'/vendor/symfony/console/Application.php',
    // $base.'/vendor/monolog/monolog/src/Monolog/Handler/HandlerInterface.php',
    // $base.'/vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php',
    // $base.'/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php',
    // $base.'/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php',

    # phalcon slayer
    $base.'/vendor/phalconslayer/framework/src/Clarity/Kernel/KernelTrait.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Kernel/Kernel.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Services/Container.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Services/ServiceMagicMethods.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/ServiceProvider.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/Log.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/Aliaser.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/Application.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/Auth.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/Cache.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/CollectionManager.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/Console.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/Crypt.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/DB.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/Dispatcher.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/ErrorHandler.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/Filter.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/Flash.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/FlashBag.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/Flysystem.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Lang/LangServiceProvider.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Mail/MailServiceProvider.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/MetadataAdapter.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/Module.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/Mongo.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/Queue.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/Redirect.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/Request.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/Response.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/Router.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/RouterAnnotations.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/Session.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Providers/URL.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/View/ViewServiceProvider.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Facades/Auth.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Facades/Facade.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Facades/Cache.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Facades/Config.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Facades/DB.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Facades/Flysystem.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Facades/FlysystemManager.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Facades/Filter.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Facades/Flash.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Facades/FlashBag.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Lang/LangFacade.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Facades/Log.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Mail/MailFacade.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Facades/Queue.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Facades/Redirect.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Facades/Request.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Facades/Response.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Facades/Route.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Facades/Security.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Facades/Session.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Facades/Tag.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Facades/URL.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Facades/View.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Support/Auth/Auth.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/SlayerCommand.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/App/ControllerCommand.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/App/ModuleCommand.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/App/RouteCommand.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/Clear/ClearTrait.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/Clear/AllCommand.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/Clear/CacheCommand.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/Clear/CompiledCommand.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/Clear/LogsCommand.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/Clear/SessionCommand.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/Clear/ViewsCommand.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/DB/SeedFactory.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/Mail/InlinerCommand.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/Make/CollectionCommand.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/Make/ConsoleCommand.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/Make/ModelCommand.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/Script/RunCommand.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/Server/OptimizeCommand.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/Server/ServeCommand.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/Server/EnvCommand.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/Vendor/NewCommand.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Console/Vendor/PublishCommand.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Support/Phinx/Console/Command/Traits/MigrationTrait.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Support/Phinx/Console/Command/Traits/ConfigurationTrait.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Support/Phinx/Console/Command/Create.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Support/Phinx/Console/Command/Migrate.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Support/Phinx/Console/Command/Rollback.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Support/Phinx/Console/Command/Traits/SeedTrait.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Support/Phinx/Console/Command/SeedCreate.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Support/Phinx/Console/Command/SeedRun.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Support/Phinx/Console/Command/Status.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Exceptions/Handler.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Contracts/Flysystem/AdapterInterface.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Lang/Lang.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Mail/Mail.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Contracts/Mail/MailInterface.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Mail/SwiftMailer/SwiftMailer.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Support/WithMagicMethodTrait.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Support/Redirect/Redirect.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Support/Phalcon/Http/Request.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Support/Phalcon/Mvc/Router.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Support/Phalcon/Session/Files.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Support/Phalcon/Mvc/URL.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Support/Phalcon/Mvc/Router.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Support/Phalcon/Mvc/Collection.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Support/Phalcon/Mvc/View.php',
    $base.'/vendor/phalconslayer/framework/src/Clarity/Support/Helpers/init.php',
];
